on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  detector:
    name: Detect unintentional file ( not "*.json" )
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: exec detection
      working-directory: jsondir
      run: find . -type f -not -name "*.json" -exec false {} + -print
